server:
  port: 16888

spring:
  ## 数据库基本信息配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/lb-abcd?currentSchema=test
    username: lbcs
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      connection-timeout: 60000
      validation-timeout: 10000

  ## JPA相关配置
  jpa:
    show-sql: true
    # 框架自动创建或更新表结构
    hibernate:
      ddl-auto: update

  ## jackson相关配置
  jackson:
    # 返回JSON全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss

  ## Redis相关配置
  redis:
    host: 127.0.0.1
    port: 6379
    # 链接超时时间
    timeout: PT10S
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: PT10S
        # 连接池中的最大空闲连接 默认 8
        max-idle: 30
        # 连接池中的最小空闲连接 默认 0
        min-idle: 1

## mybatis-plus相关配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置mapper xml文件的路径
  mapper-locations:

## swagger相关配置
swagger2:
  # 开关【true:开; false:关】
  enable: true
