server:
  port: 16888

spring:
  ## 数据库基本信息配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/lb-abcd?currentSchema=sys&stringtype=unspecified
    username: lbcs
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      connection-timeout: 60000
      validation-timeout: 10000

  ## JPA相关配置
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
    # 框架自动创建或更新表结
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        temp:
          use_jdbc_metadata_defaults: false

  ## jackson相关配置
  jackson:
    # 返回JSON全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss

  ## Redis相关配置
  redis:
    host: 127.0.0.1
    port: 6379
    # 链接超时时间
    timeout: PT10S
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: PT10S
        # 连接池中的最大空闲连接 默认 8
        max-idle: 30
        # 连接池中的最小空闲连接 默认 0
        min-idle: 1

## mybatis-plus相关配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

  # 配置mapper xml文件的路径
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.lb.abcd.**.entity

## JWT相关配置
jwt:
  # AccessToken 过期时间单位分钟
  EXPIRE_TIME: 5
  # RefreshToken 过期时间单位分钟
  REFRESH_EXPIRE_TIME: 30
  # 密钥盐
  TOKEN_SECRET: 50eFa4d9W8ba4d*bb276f^11


## swagger相关配置
swagger2:
  # 开关【true:开; false:关】
  enable: true
